// Generated by CoffeeScript 1.6.3
var SingleWrap, fs;

fs = require("fs");

module.exports = SingleWrap = (function() {
  SingleWrap.prototype.brunchPlugin = true;

  SingleWrap.prototype.type = 'javascript';

  SingleWrap.prototype.extension = 'js';

  function SingleWrap(config) {
    var k, userConfig, _ref;
    this.config = config;
    this.singleWrapConfig = {
      wrap: function(file, code) {
        return "(function(){\n" + code + "\n})();";
      }
    };
    userConfig = ((_ref = this.config.plugins) != null ? _ref.singlewrap : void 0) || {};
    for (k in this.singleWrapConfig) {
      if (userConfig[k]) {
        this.singleWrapConfig[k] = userConfig[k];
      }
    }
  }

  SingleWrap.prototype.onCompile = function(generatedFiles) {
    var code, file, path, _i, _len, _results;
    _results = [];
    for (_i = 0, _len = generatedFiles.length; _i < _len; _i++) {
      file = generatedFiles[_i];
      path = file.path;
      code = fs.readFileSync(path) + "";
      _results.push(fs.writeFileSync(path, this.singleWrapConfig.wrap(path, code)));
    }
    return _results;
  };

  return SingleWrap;

})();
